project_id = "dvifxaygfrhhzmnmyiyp"

[functions.update-order-status]
verify_jwt = false

[functions.admin-update-order]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.simulate-order-webhook]
verify_jwt = true

[functions.generate-logo]
verify_jwt = false
