project_id = "dvifxaygfrhhzmnmyiyp"

[functions.create-shopify-order]
verify_jwt = true

[functions.create-shopify-checkout]
verify_jwt = true

[functions.update-order-status]
verify_jwt = false

[functions.admin-update-order]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
