project_id = "dvifxaygfrhhzmnmyiyp"

[functions.update-order-status]
verify_jwt = false

[functions.admin-update-order]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.lookup-order-by-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.simulate-order-webhook]
verify_jwt = true

[functions.preview-supplier-order-pdf]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.change-own-password]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.ingest-supplier-emails]
verify_jwt = false
